# Generated by Django 5.1.2 on 2024-11-04 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_creado', models.DateTimeField(auto_now_add=True)),
                ('historial_actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('preparación', 'Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='preparación', max_length=20)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
