# Generated by Django 5.1.2 on 2024-11-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historialestados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_creado', models.DateTimeField(auto_now_add=True)),
                ('pedido_actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.historialestados')),
            ],
        ),
    ]
