# Generated by Django 5.1.2 on 2024-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago_creado', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago_actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_compra', models.DateField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
