# Generated by Django 5.1.2 on 2024-11-04 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mesasestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_creada', models.DateTimeField(auto_now_add=True)),
                ('mesa_actualizada', models.DateTimeField(auto_now=True)),
                ('numero_mesa', models.IntegerField()),
                ('capacidad_mesa', models.IntegerField()),
                ('disponiblilidad_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesasestado')),
            ],
        ),
    ]
