# Generated by Django 5.1.2 on 2024-11-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_creado', models.DateTimeField(auto_now_add=True)),
                ('comentario_actualizado', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('id_menu_comentarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
            ],
        ),
    ]
