# Generated by Django 5.1.2 on 2024-11-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion_creada', models.DateTimeField(auto_now_add=True)),
                ('notificacion_actualizada', models.DateTimeField(auto_now=True)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField()),
            ],
        ),
    ]
