# Generated by Django 5.1.2 on 2024-11-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_creada', models.DateTimeField(auto_now_add=True)),
                ('reserva_actualizada', models.DateTimeField(auto_now=True)),
                ('fecha_reserva', models.DateTimeField()),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesas')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metododepago')),
            ],
        ),
    ]
